### ISSUE TITLE
Error creating a folder

### ISSUE THREAD

**Issue by dsakura** [jsmaskeen/sa-drive#19]
```
2024-12-04:19:26:23,204 INFO     [_internal.py:97] 127.0.0.1 - - [04/Dec/2024 19:26:23] "←[35m←[1mPOST /create_folder HTTP/1.1←[0m" 500 -
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\pydrive2\files.py", line 728, in _FilesInsert
    .execute(http=self.http)
     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\googleapiclient\http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/drive/v2/files?supportsAllDrives=true&alt=json returned "File not found: 1LDY4zZ4l20hex0ETSlx6tRMubKfXd_VU". Details: "[{'message': 'File not found: 1LDY4zZ4l20hex0ETSlx6tRMubKfXd_VU', 'domain': 'global', 'reason': 'notFound', 'location': 'file', 'locationType': 'other'}]">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OneDrive\Documentos\sadrive-ponte\sa-drive-1.0.2\main.py", line 55, in decorated_view
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\OneDrive\Documentos\sadrive-ponte\sa-drive-1.0.2\main.py", line 245, in create_folder
    f = drive.create_folder(foldername,parent_id)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OneDrive\Documentos\sadrive-ponte\sa-drive-1.0.2\helpers\drive_util.py", line 40, in create_folder
    newFolder.Upload()
  File "C:\Python312\Lib\site-packages\pydrive2\files.py", line 514, in Upload
    self._FilesInsert(param=param)
  File "C:\Python312\Lib\site-packages\pydrive2\auth.py", line 85, in _decorated
    return decoratee(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\pydrive2\files.py", line 731, in _FilesInsert
    raise ApiRequestError(error)
pydrive2.files.ApiRequestError: <HttpError 404 when requesting https://www.googleapis.com/drive/v2/files?supportsAllDrives=true&alt=json returned "File not found: 1LDY4zZ4l20hex0ETSlx6tRMubKfXd_VU". Details: "[{'message': 'File not found: 1LDY4zZ4l20hex0ETSlx6tRMubKfXd_VU', 'domain': 'global', 'reason': 'notFound', 'location': 'file', 'locationType': 'other'}]">
```
Many thanks

**Comment by dsakura** [comment]
It seems to me that even creating this drive with everything configured from the Google account, it links some part of the process to another email of mine. Would this file be on my Windows system? And again, is it possible to run 2 drives on the same computer for 2 different accounts? It's been difficult.
Thanks

**Comment by jsmaskeen** [comment]
Did you give editor access to the Google group of your service accounts to the folder "1LDY4zZ4l20hex0ETSlx6tRMubKfXd_VU" ?

Also, it is possible to run two sadrives in CLI, though it's a little tedious.

Suppose you have two config dirs, eg:
config_dir1 (it has accounts/ and config.json)
config_dir2 (it also has some other accounts/ and config.json)

So suppose you want to use the drive1 (associated with config_dir1), then you need to do:
`sadrive config set-dir path/to/config_dir1`

Do you upload commands

Then say you want to switch to the drive2, you need to do
`sadrive config set-dir path/to/config_dir2`

Now uploads will happen in drive2.

**Comment by dsakura** [comment]
Yes, and it gave me a problem, now that I created a new group of emails to use with the click I can not say if it will work with Gui, but for me it is already good, a use account Gui and another CLI. And it is an easy alternative to also use the 2 accounts with CLI.
Thanks!
