### ISSUE TITLE
SSL Error when uploading file

### ISSUE THREAD

**Issue by Sofie99** [jsmaskeen/sa-drive#6]
hi, love this app.. 
i have problem when uploading file
here's my log
```
Exception in thread Thread-232 (upload_file):
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "D:\Programs\sa-drive-main\main.py", line 131, in run
    self._return = self._target(*self._args,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\sa-drive-main\main.py", line 113, in upload_file
    for prog in worker:
  File "D:\Programs\sa-drive-main\helpers\general.py", line 6, in __iter__
    self.value = yield from self.gen
                 ^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\sa-drive-main\helpers\drive_util.py", line 68, in upload_file
    status, response = request.next_chunk()
                       ^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\sa-drive-main\venv\Lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\sa-drive-main\venv\Lib\site-packages\googleapiclient\http.py", line 1084, in next_chunk
    resp, content = http.request(
                    ^^^^^^^^^^^^^
  File "D:\Programs\sa-drive-main\venv\Lib\site-packages\oauth2client\transport.py", line 173, in new_request
    resp, content = request(orig_request_method, uri, method, body,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\sa-drive-main\venv\Lib\site-packages\oauth2client\transport.py", line 280, in request
    return http_callable(uri, method=method, body=body, headers=headers,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\sa-drive-main\venv\Lib\site-packages\httplib2\__init__.py", line 1724, in request
    (response, content) = self._request(
                          ^^^^^^^^^^^^^^
  File "D:\Programs\sa-drive-main\venv\Lib\site-packages\httplib2\__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\sa-drive-main\venv\Lib\site-packages\httplib2\__init__.py", line 1367, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1327, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1373, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1322, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1120, in _send_output
    self.send(chunk)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1045, in send
    self.sock.sendall(data)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1212, in sendall
    v = self.send(byte_view[count:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1181, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2406)
```

This error only occurs when uploading a larger folder, (in my case > 3gb)
hope you can help...

**Comment by jsmsj** [comment]
which python version are you using ?

**Comment by ssobii2** [comment]
Same error for me, using python 3.11. If there are too many files I get a similar error.
